class IClientRemoteStorageMap
{
	virtual uint32 FileWrite( uint32, ERemoteStorageFileRoot, const char *, const void *, int32 ) = 0;
	virtual uint32 GetFileSize( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint32 FileRead( uint32, ERemoteStorageFileRoot, const char *, void *, int32 ) = 0;
	virtual uint8 FileForget( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint8 FileDelete( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint64 FileShare( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint8 FileExists( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint8 FilePersisted( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint64 GetFileTimestamp( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint8 SetSyncPlatforms( uint32, ERemoteStorageFileRoot, const char *, ERemoteStoragePlatform ) = 0;
	virtual uint32 GetSyncPlatforms( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint32 GetFileCount( uint32, bool ) = 0;
	virtual const char * GetFileNameAndSize( uint32, int32, ERemoteStorageFileRoot *, int32 *, bool ) = 0;
	virtual uint8 GetQuota( uint32, int32 *, int32 * ) = 0;
	virtual uint8 IsCloudEnabledForAccount() = 0;
	virtual uint8 IsCloudEnabledForApp( uint32 ) = 0;
	virtual unknown_ret SetCloudEnabledForApp( uint32, bool ) = 0;
	virtual uint64 UGCDownload( uint64 ) = 0;
	virtual uint8 GetUGCDetails( uint64, uint32 *, char **, int32 *, CSteamID * ) = 0;
	virtual uint32 UGCRead( uint64, void *, int32 ) = 0;
	virtual uint32 GetCachedUGCCount() = 0;
	virtual uint64 GetCachedUGCHandle( int32 ) = 0;
	virtual uint32 FilePersist( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint8 FileFetch( uint32, ERemoteStorageFileRoot, const char * ) = 0;
	virtual uint8 ResolvePath( uint32, ERemoteStorageFileRoot, const char *, char *, uint32 ) = 0;
	virtual void SetCloudEnabledForAccount( bool ) = 0;
	virtual void LoadLocalFileInfoCache( uint32 ) = 0;
	virtual void EvaluateRemoteStorageSyncState( uint32 ) = 0;
	virtual uint32 GetRemoteStorageSyncState( uint32 ) = 0;
	virtual uint8 HaveLatestFilesLocally( uint32 ) = 0;
	virtual uint8 GetConflictingFileTimestamps( uint32, uint32 *, uint32 * ) = 0;
	virtual uint8 ResolveSyncConflict( uint32, bool ) = 0;
	virtual uint8 SynchronizeApp( uint32, bool, bool ) = 0;
	virtual uint8 IsAppSyncInProgress( uint32 ) = 0;
	virtual uint32 ERemoteStorageFileRootFromName( const char * ) = 0;
	virtual const char * PchNameFromERemoteStorageFileRoot( ERemoteStorageFileRoot ) = 0;
	virtual uint8 ResetFileRequestState( uint32 ) = 0;
};

